### ISSUE TITLE
Enable LXT2 support

### ISSUE THREAD

**Issue by tfors** [conda-forge/iverilog-feedstock#2]
vvp gives the following error when run with the -lxt2 option:

`LXT2 support disabled since zlib not available`

it seems zlib is missing from the build environment

**Comment by carlodri** [comment]
fixed in latest 10.2 release

**Comment by thecriticalpoint** [comment]
I get this "LXT2 support disabled" as well. I see the last note was that this was fixed in 10.2. My manfile shows version 12.0.

This occurs in a 32bit Linux Mint VM and in a 64bit Ubuntu WSL installation. Both were installed using apt.

What's the way to get LXT2 support?
